- name: Install Jenkins via Ansible
  hosts: l
  become: true
  become_method: sudo
  

  tasks:
    - name: update system
      apt:
        update_cache: yes
    - name: Install Python
      apt:
        name: python
        state: present
    - name: update cache
      apt:
       update_cache: yes
   -  name: install pip
      package:
       name: "{{item}}"
       state: present
      with_items:
       - python3
       - python3-pip
   - name: install flask
     shell: pip3 install flask flask-SQLAlchemy
