- name: Install Jenkins via Ansible
  hosts: l
  become: true
  become_method: sudo
  tasks:
   - name: update_cache
     apt: 
      update_cache: yes
      force_apt_get: true
   - name: Install Python 
     apt:
        name: python
        state: present
   - name: install pip
     package:
      name: "{{item}}"
      state: present
     with_items:
       - python3
       - python3-pip
   - name: install package
     shell: pip3 install flask flask-SQLAlchemy
