- name: Install Jenkins via Ansible
  hosts: l
  become: true
  become_method: sudo
  

  tasks:
    - name: update system
      apt:
        update_cache: yes
        force_apt_get: yes
    - name: java
      apt:
        name: openjdk-11-jre
        state: present
        force_apt_get: yes

    - name: install packages
      apt:
       name:
        - wget
       state: present
       force_apt_get: yes
    - name: Add Jenkins apt key
      shell: curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

    - name: Add Jenkins apt repository
      shell: echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: Install Jenkins 
      apt:
        update_cache: yes
        force_apt_get: yes
        install_recommends: yes
    - name: install jenkins
      apt: 
       name: jenkins
       state: latest
       force_apt_get: yes
       install_recommends: yes
    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: true
