# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: my-pv
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /data/my-app

# ---


# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: my-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi


# ---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: backends
  template:
    metadata:
      labels:
        run: backends
    spec:
      containers:
         - name: database-container
           image: rupali1520/todo:version1
           env:
             - name: DATABASE_URL
               value: "sqlite:///app/todo.db"
           volumeMounts:
             - name: data-volume
               mountPath: /app
        
      volumes:
       - name: data-volume
         hostPath:
          path: /data/db  
          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: todo-app
  template:
    metadata:
      labels:
        run: todo-app
    spec:
      containers:
         - name: frontend-container
           image: rupali1520/todo:version1
           ports:
             - containerPort: 5000
           volumeMounts:
             - name: data-volume
               mountPath: /app
      volumes:
       - name: data-volume
         hostPath:
          path: /data/db

---

apiVersion: v1
kind: Service
metadata:
  name: todo-app
  labels:
    run: todo-app

spec:
  selector:
    run: todo-app
  type: NodePort
  ports:
    - port: 5000
      protocol: "TCP"
      targetPort: 5000
      nodePort: 30301
